spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: wbx1998

# MyBatis
mybatis:
  # 搜索指定包名
  type-aliases-package: com.oristand.b2b.manage.db.mysql.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml
# MyBatis 打印SQL
logging:
  level:
    com.example.carplatform.mapper: debug
    mapper: debug